### ISSUE TITLE
Schema-registry service does not work

### ISSUE THREAD

**Issue by ZeroWiggliness** [bbaugher/confluent#11]
Starting and stopping the service does not work.  The class attribute is wrong and should be changed from 

default["confluent"]["schema-registry"]["class"] = "io.confluent.kafka.schemaregistry.rest.Main"

to

default["confluent"]["schema-registry"]["class"] = "io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain"

which seems to work.  

Sorry due to company policy I cannot commit to open source projects hence the issue.

**Comment by bbaugher** [comment]
Thanks. Fixed by, https://github.com/bbaugher/confluent/commit/fb335cc630feb16ce130a102e1de3c621f97f2a3
