### ISSUE TITLE
Changes not reflecting in local cookbook

### ISSUE THREAD

**Issue by piyushchordia** [bbaugher/confluent#27]
@bbaugher we use confluent cookbook in our repos as core and make necessary changes in local. 
We provide "depends 'confluent'" in our metadata.rb but recent changes are not getting reflecting after chef build and run. Can you please suggest on how we can pull recent changes.

**Comment by bbaugher** [comment]
Well I haven't released the version with your change. Are you using Berkshelf to pull down the cookbook? Could either try installing locally with knife and pushing it to your chef server or configure your Berksfile to point to the git repo and master branch

**Comment by bbaugher** [comment]
I cleaned up a few things and release the 1.2.0 version, you should be able to consume that from supermarket
