### ISSUE TITLE
Support for Confluent 3.3?

### ISSUE THREAD

**Issue by darrenhaken** [bbaugher/confluent#30]

**Comment by bbaugher** [comment]
This should work by just tweak [version](https://github.com/bbaugher/confluent/blob/master/attributes/default.rb#L3-L4) or maybe URL attributes. Whats the issue?

**Comment by piyushchordia** [comment]
@darrenhaken 
You would be required to change below parameter
default["confluent"]["version"] = "3.3.0"
default['confluent']['kafka']['class'] = 'io.confluent.support.metrics.SupportedKafka'
