### ISSUE TITLE
Release support for kafka and schema-registry

### ISSUE THREAD

**Issue by patoarvizu** [bbaugher/confluent#8]
Is the next release going to be out soon? I'd like to be able to use the recipes for kafka and schema registry. I'm cloning the repository at master but I'd like to be able to pin a version.

**Comment by bbaugher** [comment]
Yes that was the idea and then I forgot about doing this. I was hoping to do #3 otherwise you can't even set memory. I'll see what I can do tonight otherwise I may just release as is.

**Comment by bbaugher** [comment]
This was released, https://github.com/bbaugher/confluent/tree/0.2.0
